# apache_tis.yml

- name: Config of the Apache server
  hosts: webserver
  become: true

  vars:
    apache_root: /var/www/html
    apache_user: www-data
    zip_files_path: html/archives/*.zip

  tasks:
    - name: Install Apache (Debian/Ubuntu)
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Deploy the config file Apache
      ansible.builtin.template:
        src: templates/apache.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      vars:
        server_name: https://eu-tis.trout.software/
        apache_root: /var/www/html
      notify: Restart Apache

    - name: Copy of the static files in the web repertory
      ansible.builtin.copy:
        src: html/index.html
        dest: "{{ apache_root }}/index.html"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'

    - name: Copy the learn_more.html page to web root
      ansible.builtin.copy:
        src: html/learn_more.html
        dest: "{{ apache_root }}/learn_more.html"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'

    - name: Create main archive directory for ZIP files
      ansible.builtin.file:
        path: "{{ apache_root }}/archives"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0755'

    - name: Create threat-actors subdirectory
      ansible.builtin.file:
        path: "{{ apache_root }}/archives/threat-actors"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0755'

    - name: Create products subdirectory
      ansible.builtin.file:
        path: "{{ apache_root }}/archives/products"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0755'

    - name: Copy threat-actors ZIP archives to the server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ apache_root }}/archives/threat-actors/"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'
      with_fileglob:
        - "/home/user/wk/eu-tis/zip/threat-actors/*.zip"

    - name: Copy products ZIP archives to the server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ apache_root }}/archives/products/"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'
      with_fileglob:
        - "/home/user/wk/eu-tis/zip/products/*.zip"

    - name: Generate the archives.html page dynamically
      ansible.builtin.template:
        src: templates/archives.html.j2
        dest: "{{ apache_root }}/archives.html"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'
      vars:
        threat_actors: "{{ lookup('ansible.builtin.fileglob', '/home/user/wk/eu-tis/zip/threat-actors/*.zip', wantlist=True) | map('basename') | list }}"
        products: "{{ lookup('ansible.builtin.fileglob', '/home/user/wk/eu-tis/zip/products/*.zip', wantlist=True) | map('basename') | list }}"

    - name: Create images directory on the server
      ansible.builtin.file:
        path: "{{ apache_root }}/images"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0755'

    - name: Copy images directory contents to web root
      ansible.builtin.copy:
        src: html/images/
        dest: "{{ apache_root }}/images/"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'
        remote_src: no

    - name: Create fonts directory on the server
      ansible.builtin.file:
        path: "{{ apache_root }}/fonts"
        state: directory
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0755'

    - name: Copy fonts directory contents to web root
      ansible.builtin.copy:
        src: html/fonts/
        dest: "{{ apache_root }}/fonts/"
        owner: "{{ apache_user }}"
        group: "{{ apache_user }}"
        mode: '0644'
        remote_src: no

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"
